# Netlify configuration file

[build]
  # Directory with the build output
  publish = "dist"
  
  # Build command
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"